# Generated by Django 5.2.6 on 2025-09-29 17:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_remove_favorite_moments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Keep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keep_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('text', 'Text Note'), ('milestone', 'Milestone')], default='photo', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_of_memory', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keeps', to='users.circle')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keeps_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_of_memory', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KeepComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='keeps.keep')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keep_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='KeepMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(upload_to='keeps/%Y/%m/%d/')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=10)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('upload_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('keep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='keeps.keep')),
            ],
            options={
                'ordering': ['upload_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='KeepReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', '👍 Like'), ('love', '❤️ Love'), ('laugh', '😂 Laugh'), ('wow', '😮 Wow'), ('celebrate', '🎉 Celebrate')], default='like', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('keep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='keeps.keep')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keep_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_type', models.CharField(choices=[('first_word', 'First Word'), ('first_steps', 'First Steps'), ('first_tooth', 'First Tooth'), ('first_day_school', 'First Day of School'), ('birthday', 'Birthday'), ('height_weight', 'Height & Weight Check'), ('other', 'Other')], default='other', max_length=30)),
                ('age_at_milestone', models.CharField(blank=True, help_text="e.g., '18 months', '2 years 3 months'", max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('is_first_time', models.BooleanField(default=True)),
                ('child_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='users.childprofile')),
                ('keep', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='milestone', to='keeps.keep')),
            ],
            options={
                'ordering': ['-keep__date_of_memory'],
            },
        ),
        migrations.AddIndex(
            model_name='keep',
            index=models.Index(fields=['circle', '-date_of_memory'], name='keeps_keep_circle__f5e339_idx'),
        ),
        migrations.AddIndex(
            model_name='keep',
            index=models.Index(fields=['created_by', '-created_at'], name='keeps_keep_created_cb57a8_idx'),
        ),
        migrations.AddIndex(
            model_name='keep',
            index=models.Index(fields=['keep_type'], name='keeps_keep_keep_ty_52ee0e_idx'),
        ),
        migrations.AddIndex(
            model_name='keepcomment',
            index=models.Index(fields=['keep', 'created_at'], name='keeps_keepc_keep_id_979e78_idx'),
        ),
        migrations.AddIndex(
            model_name='keepmedia',
            index=models.Index(fields=['keep', 'upload_order'], name='keeps_keepm_keep_id_cc2d5b_idx'),
        ),
        migrations.AddIndex(
            model_name='keepreaction',
            index=models.Index(fields=['keep', '-created_at'], name='keeps_keepr_keep_id_594c7d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='keepreaction',
            unique_together={('keep', 'user')},
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['child_profile'], name='keeps_miles_child_p_8a1e8f_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['milestone_type'], name='keeps_miles_milesto_e58d60_idx'),
        ),
    ]
