# Generated by Django 5.2.6 on 2025-09-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keep',
            name='keep_type',
            field=models.CharField(choices=[('note', 'Note'), ('media', 'Media'), ('milestone', 'Milestone')], default='note', max_length=20),
        ),
    ]
