# Generated by Django 5.2.6 on 2025-10-23 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keeps', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='keep',
            name='circle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keeps', to='users.circle'),
        ),
        migrations.AddField(
            model_name='keep',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keeps_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='keepcomment',
            name='keep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='keeps.keep'),
        ),
        migrations.AddField(
            model_name='keepcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keep_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='keepmedia',
            name='keep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='keeps.keep'),
        ),
        migrations.AddField(
            model_name='keepreaction',
            name='keep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='keeps.keep'),
        ),
        migrations.AddField(
            model_name='keepreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keep_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mediaupload',
            name='keep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='keeps.keep'),
        ),
        migrations.AddField(
            model_name='mediaupload',
            name='media_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_record', to='keeps.keepmedia'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='child_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='users.childprofile'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='keep',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='milestone', to='keeps.keep'),
        ),
        migrations.AddIndex(
            model_name='keep',
            index=models.Index(fields=['circle', '-date_of_memory'], name='keeps_keep_circle__f5e339_idx'),
        ),
        migrations.AddIndex(
            model_name='keep',
            index=models.Index(fields=['created_by', '-created_at'], name='keeps_keep_created_cb57a8_idx'),
        ),
        migrations.AddIndex(
            model_name='keep',
            index=models.Index(fields=['keep_type'], name='keeps_keep_keep_ty_52ee0e_idx'),
        ),
        migrations.AddIndex(
            model_name='keepcomment',
            index=models.Index(fields=['keep', 'created_at'], name='keeps_keepc_keep_id_979e78_idx'),
        ),
        migrations.AddIndex(
            model_name='keepmedia',
            index=models.Index(fields=['keep', 'upload_order'], name='keeps_keepm_keep_id_cc2d5b_idx'),
        ),
        migrations.AddIndex(
            model_name='keepmedia',
            index=models.Index(fields=['media_type'], name='keeps_keepm_media_t_6ddb11_idx'),
        ),
        migrations.AddIndex(
            model_name='keepreaction',
            index=models.Index(fields=['keep', '-created_at'], name='keeps_keepr_keep_id_594c7d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='keepreaction',
            unique_together={('keep', 'user')},
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['child_profile'], name='keeps_miles_child_p_8a1e8f_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['milestone_type'], name='keeps_miles_milesto_e58d60_idx'),
        ),
    ]
