# Generated by Django 5.2.6 on 2025-09-29 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keeps', '0002_alter_keep_keep_type'),
    ]

    operations = [
    ]
