# Generated by Django 5.2.6 on 2025-10-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeps', '0003_auto_20250929_1847'),
    ]

    operations = [
        # Remove old media_file field
        migrations.RemoveField(
            model_name='keepmedia',
            name='media_file',
        ),
        # Add new storage key fields
        migrations.AddField(
            model_name='keepmedia',
            name='storage_key_original',
            field=models.CharField(max_length=500, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keepmedia',
            name='storage_key_thumbnail',
            field=models.CharField(max_length=500, blank=True),
        ),
        migrations.AddField(
            model_name='keepmedia',
            name='storage_key_gallery',
            field=models.CharField(max_length=500, blank=True),
        ),
        # Add new metadata fields
        migrations.AddField(
            model_name='keepmedia',
            name='original_filename',
            field=models.CharField(max_length=255, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keepmedia',
            name='content_type',
            field=models.CharField(max_length=100, default='application/octet-stream'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keepmedia',
            name='width',
            field=models.PositiveIntegerField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='keepmedia',
            name='height',
            field=models.PositiveIntegerField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='keepmedia',
            name='thumbnails_generated',
            field=models.BooleanField(default=False),
        ),
        # Add indexes
        migrations.AddIndex(
            model_name='keepmedia',
            index=models.Index(fields=['keep', 'upload_order'], name='keeps_keepm_keep_id_e5f7a2_idx'),
        ),
        migrations.AddIndex(
            model_name='keepmedia',
            index=models.Index(fields=['media_type'], name='keeps_keepm_media_t_c8b4d1_idx'),
        ),
    ]
