# Generated by Django 5.2.6 on 2025-10-01 19:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeps', '0004_update_keepmedia_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=10)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField()),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('upload_order', models.PositiveSmallIntegerField(default=0)),
                ('temp_file_path', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validating', 'Validating'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='keepmedia',
            name='keeps_keepm_keep_id_e5f7a2_idx',
        ),
        migrations.RenameIndex(
            model_name='keepmedia',
            new_name='keeps_keepm_media_t_6ddb11_idx',
            old_name='keeps_keepm_media_t_c8b4d1_idx',
        ),
        migrations.AddField(
            model_name='mediaupload',
            name='keep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='keeps.keep'),
        ),
        migrations.AddField(
            model_name='mediaupload',
            name='media_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_record', to='keeps.keepmedia'),
        ),
    ]
