# Generated by Django 5.2.6 on 2026-09-05 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeps', '0004_tinybeanssyncrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='keepcomment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Comment this one replies to (same keep); null for top-level comments', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='keeps.keepcomment'),
        ),
    ]
