# Generated by Django 5.2.6 on 2026-09-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeps', '0006_backfill_comment_parents'),
        ('users', '0002_add_circle_owner_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='keep',
            name='children',
            field=models.ManyToManyField(blank=True, help_text='Children this memory is about', related_name='keeps', to='users.childprofile'),
        ),
    ]
