# Generated by Django 5.2.6 on 2026-09-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("keeps", "0009_tinybeanssyncrun_account_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaupload",
            name="poster_temp_path",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
