# Generated by Django 5.2.6 on 2026-09-28 22:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeps', '0010_mediaupload_poster_temp_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeepFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('keep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='keeps.keep')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keep_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='keeps_keepf_user_id_492508_idx')],
                'unique_together': {('keep', 'user')},
            },
        ),
    ]
