# Generated by Django 5.2.6 on 2026-09-29 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeps', '0011_keepfavorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinybeansimportrecord',
            name='keep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tinybeans_import_records', to='keeps.keep'),
        ),
    ]
