# Generated by Django 5.2.6 on 2026-09-29 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeps', '0012_tinybeans_import_keep_set_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinybeansimportrecord',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tinybeans_import_records', to='keeps.keepcomment'),
        ),
        migrations.AlterField(
            model_name='tinybeansimportrecord',
            name='reaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tinybeans_import_records', to='keeps.keepreaction'),
        ),
    ]
