# Generated by Django 5.2.6 on 2026-10-04 21:23

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeps', '0013_tinybeans_import_comment_reaction_set_null'),
        ('users', '0005_user_color_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people', to='users.childprofile')),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='users.circle')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_created', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people', to='users.petprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': [django.db.models.functions.text.Lower('name'), 'id'],
            },
        ),
        migrations.CreateModel(
            name='KeepPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_tags_added', to=settings.AUTH_USER_MODEL)),
                ('keep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_tags', to='keeps.keep')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_tags', to='keeps.keepmedia')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keep_tags', to='keeps.person')),
            ],
        ),
        migrations.AddField(
            model_name='keep',
            name='people',
            field=models.ManyToManyField(blank=True, help_text='People tagged on this memory', related_name='keeps', through='keeps.KeepPerson', to='keeps.person'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(condition=models.Q(('child__isnull', False)), fields=('circle', 'child'), name='keeps_person_unique_child'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('circle', 'user'), name='keeps_person_unique_user'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(condition=models.Q(('pet__isnull', False)), fields=('circle', 'pet'), name='keeps_person_unique_pet'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(models.F('circle'), django.db.models.functions.text.Lower('name'), condition=models.Q(('child__isnull', True), ('pet__isnull', True), ('user__isnull', True)), name='keeps_person_unique_free_text_name'),
        ),
        migrations.AddConstraint(
            model_name='keepperson',
            constraint=models.UniqueConstraint(fields=('keep', 'person'), name='keeps_unique_keep_person'),
        ),
    ]
