# Generated by Django 5.2.6 on 2026-10-05 19:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeps', '0017_keepcommentmention'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthMeasurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('measured_on', models.DateField()),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('250.0'))])),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.100')), django.core.validators.MaxValueValidator(Decimal('250.000'))])),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='growth_measurements_created', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_measurements', to='keeps.person')),
            ],
            options={
                'ordering': ['measured_on', 'created_at', 'id'],
                'indexes': [models.Index(fields=['person', 'measured_on'], name='keeps_growt_person__0b3b67_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('height_cm__isnull', False), ('weight_kg__isnull', False), _connector='OR'), name='keeps_growth_height_or_weight'), models.CheckConstraint(condition=models.Q(('height_cm__isnull', True), ('height_cm__gt', 0), _connector='OR'), name='keeps_growth_height_positive'), models.CheckConstraint(condition=models.Q(('weight_kg__isnull', True), ('weight_kg__gt', 0), _connector='OR'), name='keeps_growth_weight_positive')],
            },
        ),
    ]
