# Generated by Django 5.2.6 on 2025-10-23 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='magiclogintoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magic_login_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recoverycode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trusteddevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='twofactorauditlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='twofactorcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='twofactorsettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='twofa_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='magiclogintoken',
            index=models.Index(fields=['token_hash', 'is_used'], name='auth_app_ma_tokenhash_idx'),
        ),
        migrations.AddIndex(
            model_name='magiclogintoken',
            index=models.Index(fields=['user', 'expires_at'], name='auth_app_ma_user_id_f5d5d3_idx'),
        ),
        migrations.AddIndex(
            model_name='trusteddevice',
            index=models.Index(fields=['user', 'device_id'], name='auth_app_tr_user_id_5b157e_idx'),
        ),
        migrations.AddIndex(
            model_name='trusteddevice',
            index=models.Index(fields=['expires_at'], name='auth_app_tr_expires_024162_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trusteddevice',
            unique_together={('user', 'device_id')},
        ),
        migrations.AddIndex(
            model_name='twofactorcode',
            index=models.Index(fields=['user', 'code_hash', 'is_used'], name='auth_app_tw_user_id_f20d7f_idx'),
        ),
        migrations.AddIndex(
            model_name='twofactorcode',
            index=models.Index(fields=['expires_at'], name='auth_app_tw_expires_379caf_idx'),
        ),
    ]
