# Generated by Django 5.2.6 on 2025-10-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_security_improvements'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactorsettings',
            name='sms_verified',
            field=models.BooleanField(default=False),
        ),
    ]
