# Generated by Django 5.2.6 on 2026-10-06 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_secure_pkce_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppleOAuthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_token', models.CharField(db_index=True, help_text='Unique OAuth state token', max_length=128, unique=True)),
                ('nonce', models.CharField(help_text='Nonce Apple must echo in the ID token', max_length=64)),
                ('return_uri', models.URLField(help_text="SPA URL the browser is sent to after Apple's POST")),
                ('first_name', models.CharField(blank=True, default='', help_text="Name from Apple's first POST", max_length=150)),
                ('last_name', models.CharField(blank=True, default='', help_text="Name from Apple's first POST", max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When state was created')),
                ('used_at', models.DateTimeField(blank=True, help_text='When state was used', null=True)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address that initiated OAuth')),
                ('user_agent', models.TextField(help_text='User agent that initiated OAuth')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When state expires')),
            ],
            options={
                'verbose_name': 'Apple OAuth State',
                'verbose_name_plural': 'Apple OAuth States',
                'ordering': ['-created_at'],
            },
        ),
    ]
