# Generated by Django 5.2.6 on 2025-10-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_twofactorsettings_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactorsettings',
            name='totp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
