# Generated by Django 5.2.6 on 2025-10-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_magiclogintoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleOAuthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_token', models.CharField(db_index=True, help_text='Unique OAuth state token', max_length=128, unique=True)),
                ('code_verifier', models.CharField(help_text='PKCE code verifier', max_length=128)),
                ('redirect_uri', models.URLField(help_text='OAuth redirect URI')),
                ('nonce', models.CharField(help_text='Additional CSRF protection nonce', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When state was created')),
                ('used_at', models.DateTimeField(blank=True, help_text='When state was used', null=True)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address that initiated OAuth')),
                ('user_agent', models.TextField(help_text='User agent that initiated OAuth')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When state expires (10 min)')),
            ],
            options={
                'verbose_name': 'Google OAuth State',
                'verbose_name_plural': 'Google OAuth States',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['state_token', 'used_at'], name='auth_oauth_state_idx'), models.Index(fields=['expires_at'], name='auth_oauth_expires_idx')],
            },
        ),
    ]
