# Generated by ChatGPT migration for P2 hardening

import hashlib

from django.db import migrations, models


def populate_security_fields(apps, schema_editor):
    TwoFactorCode = apps.get_model('auth_app', 'TwoFactorCode')
    TrustedDevice = apps.get_model('auth_app', 'TrustedDevice')

    for code in TwoFactorCode.objects.all().iterator():
        plain = getattr(code, 'code', '') or ''
        if plain:
            code.code_hash = hashlib.sha256(plain.encode('utf-8')).hexdigest()
            code.code_preview = plain[-6:]
        else:
            # Preserve empty defaults for legacy rows
            code.code_hash = ''
            code.code_preview = ''
        code.save(update_fields=['code_hash', 'code_preview'])

    for device in TrustedDevice.objects.all().iterator():
        user_agent = device.user_agent or ''
        ip_address = device.ip_address or ''
        device.ua_hash = hashlib.sha256(user_agent.encode('utf-8')).hexdigest() if user_agent else ''
        device.ip_hash = hashlib.sha256(ip_address.encode('utf-8')).hexdigest() if ip_address else ''
        device.save(update_fields=['ua_hash', 'ip_hash'])


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_magic_login_token_hardening'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactorcode',
            name='code_hash',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='twofactorcode',
            name='code_preview',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='trusteddevice',
            name='ip_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='trusteddevice',
            name='ua_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.RemoveIndex(
            model_name='twofactorcode',
            name='auth_app_tw_user_id_e278ee_idx',
        ),
        migrations.RunPython(populate_security_fields, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='twofactorcode',
            name='code',
        ),
        migrations.AddIndex(
            model_name='twofactorcode',
            index=models.Index(fields=['user', 'code_hash', 'is_used'], name='auth_app_tw_user_codehash_idx'),
        ),
    ]
