# Generated by Django 5.2.6 on 2025-10-11 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_trusted_device_hardening'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='twofactorcode',
            new_name='auth_app_tw_user_id_f20d7f_idx',
            old_name='auth_app_tw_user_codehash_idx',
        ),
    ]
