# Generated by Django 5.2.6 on 2026-10-02 17:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keeps', '0013_tinybeans_import_comment_reaction_set_null'),
        ('users', '0005_user_color_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='users.circle')),
                ('cover_keep', models.ForeignKey(blank=True, help_text="Post whose first photo is the cover; defaults to the album's first post", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='keeps.keep')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlbumKeep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album_keeps_added', to=settings.AUTH_USER_MODEL)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_keeps', to='albums.album')),
                ('keep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_memberships', to='keeps.keep')),
            ],
            options={
                'ordering': ['added_at'],
            },
        ),
        migrations.AddField(
            model_name='album',
            name='keeps',
            field=models.ManyToManyField(blank=True, related_name='albums', through='albums.AlbumKeep', to='keeps.keep'),
        ),
        migrations.AddIndex(
            model_name='albumkeep',
            index=models.Index(fields=['keep'], name='albums_albu_keep_id_e5eaa6_idx'),
        ),
        migrations.AddConstraint(
            model_name='albumkeep',
            constraint=models.UniqueConstraint(fields=('album', 'keep'), name='albums_unique_album_keep'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['circle', '-updated_at'], name='albums_albu_circle__60347b_idx'),
        ),
    ]
