# Generated by Django 5.2.6 on 2026-10-05 19:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyRecap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month the recap covers')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('album', models.OneToOneField(blank=True, help_text='The recap album; null once it was deleted, which stops it being made again', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recap', to='albums.album')),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_recaps', to='users.circle')),
            ],
            options={
                'ordering': ['-month'],
                'constraints': [models.UniqueConstraint(fields=('circle', 'month'), name='albums_unique_monthly_recap')],
            },
        ),
    ]
