x-common-env: &django-common-env
  DJANGO_SETTINGS_MODULE: mysite.settings
  REDIS_URL: redis://redis:6379/0
  POSTGRES_DB: tinybeans
  POSTGRES_USER: tinybeans
  POSTGRES_PASSWORD: tinybeans
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  MAILJET_API_KEY: ${MAILJET_API_KEY:-}
  MAILJET_API_SECRET: ${MAILJET_API_SECRET:-}
  MAILJET_FROM_EMAIL: ${MAILJET_FROM_EMAIL:-no-reply@example.com}
  MAILJET_FROM_NAME: ${MAILJET_FROM_NAME:-Tinybeans Circles}
  MAILJET_USE_SANDBOX: ${MAILJET_USE_SANDBOX:-0}
  TWOFA_RATE_LIMIT_MAX: 0
  TWOFA_RATE_LIMIT_WINDOW: 0
  RATELIMIT_ENABLE: 0

services:
  web:
    build: .
    command: bash -lc "python manage.py migrate && python manage.py seed_demo_data && python manage.py runserver 0.0.0.0:8000"
    working_dir: /app/mysite
    volumes:
      - ./:/app
    environment:
      <<: *django-common-env
      DJANGO_ALLOWED_HOSTS: "*"
      TWOFA_ENCRYPTION_KEY: GCMlol1TrcGkRhSN0uW_22q9mJ0Fz8-Gjswh0UYz4mE=
    depends_on:
      - redis
      - postgres
    expose:
      - "8000"
    ports:
      - "8100:8000"

  # Vite dev server for React frontend
  web-frontend:
    image: node:20-alpine
    command: sh -c "npm install && npm run dev"
    working_dir: /app
    volumes:
      - ./web:/app
    ports:
      - "3053:3000"
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true

  celery-worker-1:
    build: .
    command: celery -A mysite worker -l INFO -n worker1@%h
    working_dir: /app/mysite
    volumes:
      - ./:/app
    environment:
      <<: *django-common-env
    depends_on:
      - redis
      - postgres

  celery-worker-2:
    build: .
    command: celery -A mysite worker -l INFO -n worker2@%h
    working_dir: /app/mysite
    volumes:
      - ./:/app
    environment:
      <<: *django-common-env
    depends_on:
      - redis
      - postgres

  celery-worker-3:
    build: .
    command: celery -A mysite worker -l INFO -n worker3@%h
    working_dir: /app/mysite
    volumes:
      - ./:/app
    environment:
      <<: *django-common-env
    depends_on:
      - redis
      - postgres

  celery-beat:
    build: .
    command: celery -A mysite beat -l INFO
    working_dir: /app/mysite
    volumes:
      - ./:/app
    environment:
      <<: *django-common-env
    depends_on:
      - redis
      - postgres

  flower:
    build: .
    command: celery -A mysite flower --url-prefix=flower --port=5555 --address=0.0.0.0
    working_dir: /app/mysite
    volumes:
      - ./:/app
    environment:
      <<: *django-common-env
    depends_on:
      - redis
      - postgres
    expose:
      - "5555"
    ports:
      - "5656:5555"

  redis:
    image: redis:7-alpine
    expose:
      - "6379"

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "8182:5540"
    volumes:
      - redisinsight_data:/data
    depends_on:
      - redis

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: tinybeans
      POSTGRES_USER: tinybeans
      POSTGRES_PASSWORD: tinybeans
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5532:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tinybeans.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5150:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  # MinIO - S3-compatible object storage for local development
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    expose:
      - "9020"
      - "9021"
    ports:
      - "9220:9000"  # API
      - "9221:9001"  # Console

  # Initialize MinIO bucket
  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/tinybeans-media || true;
      /usr/bin/mc policy set public myminio/tinybeans-media || true;
      echo 'MinIO bucket setup complete';
      "

  # Dashy - Dashboard for all services
  dashy:
    image: lissy93/dashy:latest
    ports:
      - "4100:8080"
    volumes:
      - ./dashy-config.yml:/app/user-data/conf.yml
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:
  redisinsight_data:
  minio_data:
