"""Auth serializer package exports."""

from .account import (
    EmailVerificationConfirmSerializer,
    EmailVerificationSerializer,
    LoginSerializer,
    PasswordChangeSerializer,
    PasswordResetConfirmSerializer,
    PasswordResetRequestSerializer,
    SignupSerializer,
)
from .magic_login import (
    MagicLoginRequestSerializer,
    MagicLoginVerifySerializer,
)
from .oauth import (
    AppleOAuthInitiateResponseSerializer,
    JWTTokenSerializer,
    OAuthCallbackRequestSerializer,
    OAuthCallbackResponseSerializer,
    OAuthErrorSerializer,
    OAuthInitiateRequestSerializer,
    OAuthInitiateResponseSerializer,
    OAuthLinkRequestSerializer,
    OAuthLinkResponseSerializer,
    OAuthProvidersResponseSerializer,
    OAuthUnlinkRequestSerializer,
    OAuthUnlinkResponseSerializer,
)
from .two_factor import (
    RecoveryCodeSerializer,
    TrustedDeviceSerializer,
    TwoFactorDisableSerializer,
    TwoFactorMethodRemoveSerializer,
    TwoFactorPreferredMethodSerializer,
    TwoFactorSetupSerializer,
    TwoFactorStatusSerializer,
    TwoFactorVerifyLoginSerializer,
    TwoFactorVerifySerializer,
    TwoFactorVerifySetupSerializer,
)

__all__ = [
    "AppleOAuthInitiateResponseSerializer",
    "EmailVerificationConfirmSerializer",
    "EmailVerificationSerializer",
    "JWTTokenSerializer",
    "LoginSerializer",
    "MagicLoginRequestSerializer",
    "MagicLoginVerifySerializer",
    "OAuthCallbackRequestSerializer",
    "OAuthCallbackResponseSerializer",
    "OAuthErrorSerializer",
    "OAuthInitiateRequestSerializer",
    "OAuthInitiateResponseSerializer",
    "OAuthLinkRequestSerializer",
    "OAuthLinkResponseSerializer",
    "OAuthProvidersResponseSerializer",
    "OAuthUnlinkRequestSerializer",
    "OAuthUnlinkResponseSerializer",
    "PasswordChangeSerializer",
    "PasswordResetConfirmSerializer",
    "PasswordResetRequestSerializer",
    "RecoveryCodeSerializer",
    "SignupSerializer",
    "TrustedDeviceSerializer",
    "TwoFactorDisableSerializer",
    "TwoFactorMethodRemoveSerializer",
    "TwoFactorPreferredMethodSerializer",
    "TwoFactorSetupSerializer",
    "TwoFactorStatusSerializer",
    "TwoFactorVerifyLoginSerializer",
    "TwoFactorVerifySerializer",
    "TwoFactorVerifySetupSerializer",
]
