"""Media storage backend interface and MinIO implementation.

This module provides MinIO-based storage for media files with support
for thumbnails, gallery images, and full-size originals.
"""

import functools
import hashlib
import os
import uuid
from abc import ABC, abstractmethod
from datetime import datetime, timedelta
from datetime import timezone as dt_timezone
from typing import Any, Dict
from urllib.parse import urlparse

from django.conf import settings
from django.utils import timezone

# Presigned URLs are signed as of the start of a fixed window, so every request in
# the window gets byte-identical URLs and browsers can reuse cached files.
MAX_SIGNING_WINDOW = 86400
# S3/MinIO reject presigned URLs that live longer than seven days.
MAX_PRESIGN_EXPIRY = 7 * 86400


def signing_window_start(now, window):
    """Start of the fixed `window`-second UTC window containing `now`."""
    return datetime.fromtimestamp(int(now.timestamp()) // window * window, tz=dt_timezone.utc)


class MediaStorageBackend(ABC):
    """Abstract base class for media storage backends."""

    @abstractmethod
    def save(self, file_content: bytes, filename: str, content_type: str = None) -> str:
        """Save file content and return storage key."""
        pass

    @abstractmethod
    def delete(self, storage_key: str) -> bool:
        """Delete file from storage."""
        pass

    @abstractmethod
    def get_url(self, storage_key: str, expires_in: int = 3600) -> str:
        """Get URL for file access."""
        pass

    @abstractmethod
    def exists(self, storage_key: str) -> bool:
        """Check if file exists in storage."""
        pass

    @abstractmethod
    def get_metadata(self, storage_key: str) -> Dict[str, Any]:
        """Get file metadata."""
        pass

    def generate_storage_key(self, filename: str, content_hash: str = None) -> str:
        """Generate unique storage key for file."""
        now = timezone.now()
        date_path = now.strftime("%Y/%m/%d")

        # Use content hash if provided, otherwise generate UUID
        unique_id = content_hash[:16] if content_hash else str(uuid.uuid4()).replace("-", "")[:16]

        # Preserve file extension
        name, ext = os.path.splitext(filename)
        safe_filename = f"{unique_id}{ext.lower()}"

        return f"keeps/{date_path}/{safe_filename}"

    def calculate_content_hash(self, content: bytes) -> str:
        """Calculate SHA-256 hash of file content."""
        return hashlib.sha256(content).hexdigest()

    def calculate_file_hash(self, file_path: str) -> str:
        """SHA-256 of a file on disk, read in chunks so large videos never sit in memory."""
        digest = hashlib.sha256()
        with open(file_path, "rb") as file_handle:
            for chunk in iter(lambda: file_handle.read(1024 * 1024), b""):
                digest.update(chunk)
        return digest.hexdigest()

    def save_file(self, file_path: str, filename: str, content_type: str = None) -> str:
        """Save a file from disk and return its storage key.

        Backends that can stream from disk should override this; the default
        reads the whole file into memory.
        """
        with open(file_path, "rb") as file_handle:
            return self.save(file_handle.read(), filename, content_type)


class MinIOStorageBackend(MediaStorageBackend):
    """MinIO (S3-compatible) storage backend."""

    def __init__(self):
        try:
            from minio import Minio
            from minio.error import S3Error

            self.S3Error = S3Error
        except ImportError as err:
            raise ImportError("minio package is required for MinIO backend") from err

        self.endpoint = settings.MINIO_ENDPOINT.replace("http://", "").replace("https://", "")
        self.access_key = settings.MINIO_ACCESS_KEY
        self.secret_key = settings.MINIO_SECRET_KEY
        self.bucket_name = settings.MINIO_BUCKET_NAME
        self.secure = getattr(settings, "MINIO_USE_SSL", False)

        self.client = Minio(self.endpoint, access_key=self.access_key, secret_key=self.secret_key, secure=self.secure)

        # Presigned URLs sign the host, so when browsers reach MinIO through a
        # different URL they must be generated by a client pointed at it. The
        # region is pinned so presigning never makes a request to that host.
        public_endpoint = getattr(settings, "MINIO_PUBLIC_ENDPOINT", "")
        if public_endpoint:
            parsed = urlparse(public_endpoint)
            self.url_client = Minio(
                parsed.netloc,
                access_key=self.access_key,
                secret_key=self.secret_key,
                secure=parsed.scheme == "https",
                region=getattr(settings, "MINIO_REGION", "us-east-1"),
            )
        else:
            self.url_client = self.client

        # Ensure bucket exists
        self._ensure_bucket_exists()

    def _ensure_bucket_exists(self):
        """Create bucket if it doesn't exist."""
        try:
            if not self.client.bucket_exists(self.bucket_name):
                self.client.make_bucket(self.bucket_name)
        except self.S3Error:
            pass  # Bucket might already exist

    def save(self, file_content: bytes, filename: str, content_type: str = None) -> str:
        """Save file to MinIO."""
        from io import BytesIO

        content_hash = self.calculate_content_hash(file_content)
        storage_key = self.generate_storage_key(filename, content_hash)

        # Upload to MinIO
        self.client.put_object(
            bucket_name=self.bucket_name,
            object_name=storage_key,
            data=BytesIO(file_content),
            length=len(file_content),
            content_type=content_type or "application/octet-stream",
        )

        return storage_key

    def save_file(self, file_path: str, filename: str, content_type: str = None) -> str:
        """Stream a file from disk to MinIO (multipart for large files)."""
        storage_key = self.generate_storage_key(filename, self.calculate_file_hash(file_path))
        self.client.fput_object(
            bucket_name=self.bucket_name,
            object_name=storage_key,
            file_path=file_path,
            content_type=content_type or "application/octet-stream",
        )
        return storage_key

    def get_file_content(self, storage_key: str) -> bytes:
        """Get file content from MinIO."""
        try:
            response = self.client.get_object(self.bucket_name, storage_key)
            return response.read()
        except self.S3Error as err:
            raise FileNotFoundError(f"File not found: {storage_key}") from err
        finally:
            if "response" in locals():
                response.close()

    def delete(self, storage_key: str) -> bool:
        """Delete file from MinIO."""
        try:
            self.client.remove_object(self.bucket_name, storage_key)
            return True
        except self.S3Error:
            return False

    def get_url(self, storage_key: str, expires_in: int = 3600) -> str:
        """Get presigned URL for MinIO file access, valid for at least `expires_in` seconds.

        URLs are signed as of the start of the current window (`expires_in`, at most a
        day), so repeat requests return the same URL and the browser can serve the file
        from cache: a calendar month's thumbnails otherwise re-download on every visit.
        Signing from the window start means the URL must outlive it by `expires_in`.
        The signed Cache-Control lets browsers reuse the file without revalidating.
        """
        window = min(expires_in, MAX_SIGNING_WINDOW)
        try:
            url = self.url_client.presigned_get_object(
                bucket_name=self.bucket_name,
                object_name=storage_key,
                expires=timedelta(seconds=min(window + expires_in, MAX_PRESIGN_EXPIRY)),
                request_date=signing_window_start(timezone.now(), window),
                response_headers={"response-cache-control": f"private, max-age={expires_in}"},
            )
            return url
        except self.S3Error:
            return None

    def exists(self, storage_key: str) -> bool:
        """Check if file exists in MinIO."""
        try:
            self.client.stat_object(self.bucket_name, storage_key)
            return True
        except self.S3Error:
            return False

    def get_metadata(self, storage_key: str) -> Dict[str, Any]:
        """Get file metadata from MinIO."""
        try:
            stat = self.client.stat_object(self.bucket_name, storage_key)
            return {
                "size": stat.size,
                "content_type": stat.content_type,
                "modified": stat.last_modified,
                "etag": stat.etag,
                "storage_backend": "minio",
            }
        except self.S3Error:
            return {}


@functools.cache
def get_storage_backend() -> MediaStorageBackend:
    """Get the MinIO storage backend instance, built once per process.

    Construction checks the bucket over the network, while presigning is local
    math, so a fresh backend per URL made every signed URL pay a MinIO round
    trip. Created lazily, so forked workers (Celery) each build their own.
    """
    return MinIOStorageBackend()
