# Generated by Django 5.2.6 on 2026-09-30 18:17

from django.db import migrations, models


def push_channel_to_email(apps, schema_editor):
    # Push was never delivered; move anyone who picked it to email.
    UserNotificationPreferences = apps.get_model('users', 'UserNotificationPreferences')
    UserNotificationPreferences.objects.filter(channel='push').update(channel='email')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_circle_owner_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotificationpreferences',
            name='digest_frequency',
        ),
        migrations.RemoveField(
            model_name='usernotificationpreferences',
            name='notify_weekly_digest',
        ),
        migrations.RemoveField(
            model_name='usernotificationpreferences',
            name='push_enabled',
        ),
        migrations.AddField(
            model_name='usernotificationpreferences',
            name='notify_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usernotificationpreferences',
            name='notify_likes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usernotificationpreferences',
            name='notify_replies',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(push_channel_to_email, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='usernotificationpreferences',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'Phone')], default='email', max_length=20),
        ),
    ]
