# Generated by Django 5.2.6 on 2025-09-26 18:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_circleinvitation_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usernotificationpreferences',
            unique_together={('user', 'circle')},
        ),
        migrations.AddField(
            model_name='childprofile',
            name='favorite_moments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='pronouns',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='upgrade_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_upgrades_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='upgrade_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='upgrade_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usernotificationpreferences',
            name='digest_frequency',
            field=models.CharField(choices=[('never', 'Never'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='weekly', max_length=20),
        ),
        migrations.AddField(
            model_name='usernotificationpreferences',
            name='push_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usernotificationpreferences',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('push', 'Push')], default='email', max_length=20),
        ),
        migrations.CreateModel(
            name='ChildGuardianConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guardian_name', models.CharField(max_length=255)),
                ('guardian_relationship', models.CharField(max_length=255)),
                ('agreement_reference', models.CharField(blank=True, max_length=255)),
                ('consent_method', models.CharField(choices=[('digital_signature', 'Digital Signature'), ('paper_upload', 'Paper Upload'), ('verbal', 'Documented Verbal Consent')], max_length=32)),
                ('consent_metadata', models.JSONField(blank=True, default=dict)),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_consents_captured', to=settings.AUTH_USER_MODEL)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_consents', to='users.childprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChildUpgradeAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('request_initiated', 'Request Initiated'), ('token_reissued', 'Token Reissued'), ('token_revoked', 'Token Revoked'), ('upgrade_completed', 'Upgrade Completed')], max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_audit_logs', to='users.childprofile')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_upgrade_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
