# Generated by Django 5.2.6 on 2026-10-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_notification_event_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('it', 'Italian')], default='en', help_text="User's preferred language for the interface", max_length=10),
        ),
    ]
