# Generated by Django 5.2.6 on 2026-10-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='color_theme',
            field=models.CharField(choices=[('default', 'Default'), ('rose', 'Rose'), ('peach', 'Peach'), ('sage', 'Sage'), ('sky', 'Sky'), ('lavender', 'Lavender'), ('midnight', 'Midnight')], default='default', help_text="User's preferred color palette for the interface", max_length=20),
        ),
    ]
