# Generated by Django 5.2.6 on 2026-10-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_color_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationpreferences',
            name='digest_covered_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usernotificationpreferences',
            name='email_digest',
            field=models.BooleanField(default=False),
        ),
    ]
