# Generated by Django 5.2.6 on 2025-09-29 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_pet_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childprofile',
            name='favorite_moments',
        ),
        migrations.RemoveField(
            model_name='petprofile',
            name='favorite_moments',
        ),
    ]
