# Generated by Django 5.2.6 on 2025-10-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_favorite_moments'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('manual', 'Manual Registration'), ('google', 'Google OAuth Only'), ('hybrid', 'Both Manual and Google')], default='manual', help_text='Authentication method used by user', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='google_email',
            field=models.EmailField(blank=True, help_text='Email from Google (for debugging/tracking)', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, db_index=True, help_text='Google user ID from OAuth', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_linked_at',
            field=models.DateTimeField(blank=True, help_text='When Google account was linked', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='has_usable_password',
            field=models.BooleanField(default=True, help_text='Whether user has set a password'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_google_sync',
            field=models.DateTimeField(blank=True, help_text='Last time user info was synced from Google', null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['google_id'], name='users_google_id_idx'),
        ),
    ]
