# Generated by Django 5.2.6 on 2026-10-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_notification_email_digest'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='monthly_recap_enabled',
            field=models.BooleanField(default=False, help_text="On the 1st of each month, make an album of last month's most-liked photos"),
        ),
    ]
