# Generated by Django 5.2.6 on 2026-10-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_circle_monthly_recap_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='measurement_units',
            field=models.CharField(choices=[('imperial', 'Imperial (lb/oz, ft/in)'), ('metric', 'Metric (kg, cm)')], default='imperial', help_text='Units the user enters and reads measurements in', max_length=10),
        ),
    ]
