# Generated by Django 5.2.6 on 2025-10-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_google_oauth_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='en', help_text="User's preferred language for the interface", max_length=10),
        ),
    ]
