# Generated by Django 5.2.6 on 2026-10-05 19:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def channel_to_toggles(apps, schema_editor):
    # The single channel choice becomes its switch; new fields default to email only.
    UserNotificationPreferences = apps.get_model('users', 'UserNotificationPreferences')
    UserNotificationPreferences.objects.filter(channel='sms').update(sms_enabled=True, email_enabled=False)
    UserNotificationPreferences.objects.exclude(channel='sms').update(email_enabled=True, sms_enabled=False)


def toggles_to_channel(apps, schema_editor):
    # Going back to one channel: anyone texting keeps texting, everyone else gets email.
    UserNotificationPreferences = apps.get_model('users', 'UserNotificationPreferences')
    UserNotificationPreferences.objects.filter(sms_enabled=True).update(channel='sms')
    UserNotificationPreferences.objects.filter(sms_enabled=False).update(channel='email')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_measurement_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationpreferences',
            name='email_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usernotificationpreferences',
            name='push_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usernotificationpreferences',
            name='sms_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(channel_to_toggles, toggles_to_channel),
        migrations.RemoveField(
            model_name='usernotificationpreferences',
            name='channel',
        ),
        migrations.CreateModel(
            name='NotificationPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('code_hash', models.CharField(blank=True, default='', max_length=64)),
                ('code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('code_attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_phone', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=1000, unique=True)),
                ('p256dh', models.CharField(max_length=200)),
                ('auth', models.CharField(max_length=100)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
