# Generated by Django 5.2.6 on 2025-10-16 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def bootstrap_onboarding_status(apps, schema_editor):
    User = apps.get_model('users', 'User')
    CircleMembership = apps.get_model('users', 'CircleMembership')
    now = timezone.now()

    membership_user_ids = set(
        CircleMembership.objects.values_list('user_id', flat=True)
    )

    for user in User.objects.all().iterator():
        if user.id in membership_user_ids or user.last_login:
            new_status = 'completed'
        else:
            new_status = 'pending'

        if user.circle_onboarding_status != new_status:
            user.circle_onboarding_status = new_status
            user.circle_onboarding_updated_at = now
            user.save(update_fields=['circle_onboarding_status', 'circle_onboarding_updated_at'])
        elif new_status != 'pending' and user.circle_onboarding_updated_at is None:
            user.circle_onboarding_updated_at = now
            user.save(update_fields=['circle_onboarding_updated_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_language_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='circle_onboarding_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('dismissed', 'Dismissed')], default='pending', help_text="Progress of the user's first-circle onboarding", max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='circle_onboarding_updated_at',
            field=models.DateTimeField(blank=True, help_text='Last time the circle onboarding status changed', null=True),
        ),
        migrations.AlterField(
            model_name='circlemembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circle_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(bootstrap_onboarding_status, migrations.RunPython.noop),
    ]
