# Generated by Django 5.2.6 on 2026-10-05 22:16

from django.db import migrations, models

# Postgres won't ALTER a table in the same transaction that updated its rows, so adding
# the fields, copying the data and removing the old fields are three migrations.


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_notification_channel_toggles'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationpreferences',
            name='new_media_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usernotificationpreferences',
            name='new_media_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usernotificationpreferences',
            name='new_media_push',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usernotificationpreferences',
            name='comments_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usernotificationpreferences',
            name='comments_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usernotificationpreferences',
            name='comments_push',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usernotificationpreferences',
            name='replies_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usernotificationpreferences',
            name='replies_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usernotificationpreferences',
            name='replies_push',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usernotificationpreferences',
            name='likes_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usernotificationpreferences',
            name='likes_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usernotificationpreferences',
            name='likes_push',
            field=models.BooleanField(default=False),
        ),
    ]
