# Generated by Django 5.2.6 on 2026-10-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_notification_toggles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apple_email',
            field=models.EmailField(blank=True, help_text='Email from Apple; may be a private relay address', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='apple_id',
            field=models.CharField(blank=True, db_index=True, help_text='Apple user ID (sub) from Sign in with Apple', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='apple_linked_at',
            field=models.DateTimeField(blank=True, help_text='When the Apple account was linked', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('manual', 'Manual Registration'), ('google', 'Google OAuth Only'), ('hybrid', 'Both Manual and Google'), ('apple', 'Sign in with Apple Only')], default='manual', help_text='Authentication method used by user', max_length=20),
        ),
    ]
