name: CI

on:
  pull_request: {}

concurrency:
  group: ci-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  tests:
    permissions:
      contents: read
    uses: ljmerza/misc-actions/.github/workflows/fullstack-tests.yml@v2
    with:
      coverage-source: mysite
      codecov-backend-flags: backend
      node-version: "20"
      frontend-working-directory: web
      frontend-test-command: "npm test"
      codecov-frontend-flags: frontend
    secrets: inherit

  build:
    needs: tests
    permissions:
      contents: read
      packages: write
    uses: ljmerza/misc-actions/.github/workflows/docker-ci.yml@v2
    with:
      image-name: ghcr.io/${{ github.repository_owner }}/tinybeans
      build-target: production
    secrets: inherit
